spring:
  application:
    name: users-service
  data:
    mongodb:
      uri: mongodb+srv://users:dBjqT59dvlXb5YZO@cluster0.jvxtb.mongodb.net/microservices-users?retryWrites=true&w=majority
server:
  port: ${PORT:0}
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

